### ISSUE TITLE
Landscape Swipe, Glitch when swiping between photos, illy navigation, and "empty data"

### ISSUE THREAD

**Issue by cyberbarker** [exyte/MediaPicker#14]
Hey there!

I wanted to share some feedback on your realization that I tested. Here are a few points I noticed:

The landscape swipe to dismiss feature doesn't seem to be working as intended.
While testing, I encountered a little glitch when pressing on one photo and trying to swipe between photos. It might need some attention to work smoothly.
The layout of the navigation buttons appears to be broken. They don't seem to be displaying correctly on the screen.
I also noticed a minor issue with the label "Empty data" blinking on the screen. It's a small annoyance that could be easily fixed.
Just for your reference, I tested the realization on iOS version 16.5.1(c) using an iPhone 13 Pro.

I hope you find this feedback helpful! Have a fantastic day!

**Comment by f3dm76** [comment]
Hey @cyberbarker, thank you for your feedback, however could you please create separate issues for each problem?
- I don't think landscape mode has a swipe to dismiss. Could you please attach a video of what and where you are swiping?
- Please attach a video of a glitch, and describe it a bit more
- Please attach a screenshot and describe the desired result as compared to what you see
- Fixed in 2.0.1
Have a great day!

**Comment by f3dm76** [comment]
It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue. Have a nice day!
